un_members = [
    'Saint Kitts and Nevis', 'Saint Lucia', 'Saint Vincent and the Grenadines', 'Samoa',
    'San Marino', 'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia',
    'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia', 'Solomon Islands',
    'Somalia', 'South Africa', 'South Sudan', 'Spain', 'Sri Lanka', 'Sudan', 'Suriname',
    'Sweden', 'Switzerland', 'Syrian Arab Republic', 'Tajikistan', 'Thailand', 'Timor-Leste',
    'Togo', 'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan', 'Tuvalu',
    'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom', 'United Republic of Tanzania',
    'United States of America', 'Uruguay', 'Uzbekistan', 'Vanuatu', 'Venezuela (Bolivarian Republic of)',
    'Viet Nam', 'Yemen', 'Zambia', 'Zimbabwe', 'Afghanistan', 'Albania', 'Algeria', 'Andorra',
    'Angola', 'Antigua and Barbuda',
    'Argentina', 'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain',
    'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan',
    'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil', 'Brunei Darussalam',
    'Bulgaria', 'Burkina Faso', 'Burundi', 'Cabo Verde', 'Cambodia', 'Cameroon',
    'Canada', 'Central African Republic', 'Chad', 'Chile', 'China', 'Colombia',
    'Comoros', 'Congo', 'Costa Rica', 'Côte d\'Ivoire', 'Croatia', 'Cuba', 'Cyprus',
    'Czech Republic', 'Democratic People\'s Republic of Korea',
    'Democratic Republic of the Congo', 'Denmark', 'Djibouti', 'Dominica',
    'Dominican Republic', 'Ecuador', 'Egypt', 'El Salvador', 'Equatorial Guinea',
    'Eritrea', 'Estonia', 'Eswatini', 'Ethiopia', 'Fiji', 'Finland', 'France',
    'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana', 'Greece', 'Grenada',
    'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Honduras', 'Hungary',
    'Iceland', 'India', 'Indonesia', 'Iran (Islamic Republic of)', 'Iraq', 'Ireland',
    'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati',
    'Kuwait', 'Kyrgyzstan', 'Lao People\'s Democratic Republic', 'Latvia', 'Lebanon',
    'Lesotho', 'Liberia', 'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg',
    'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta', 'Marshall Islands',
    'Mauritania', 'Mauritius', 'Mexico', 'Micronesia (Federated States of)', 'Monaco',
    'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Nauru',
    'Nepal', 'Netherlands', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria',
    'North Macedonia', 'Norway', 'Oman', 'Pakistan', 'Palau', 'Panama',
    'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal', 'Qatar',
    'Republic of Korea', 'Republic of Moldova', 'Romania', 'Russian Federation', 'Rwanda'
]

un_members_dict = {'Afghanistan': 'AFG', 'Angola': 'AGO', 'Albania': 'ALB', 'Andorra': 'AND',
                   'United Arab Emirates': 'ARE', 'Argentina': 'ARG', 'Armenia': 'ARM', 'Antigua and Barbuda': 'ATG',
                   'Australia': 'AUS', 'Austria': 'AUT', 'Azerbaijan': 'AZE', 'Burundi': 'BDI', 'Belgium': 'BEL',
                   'Benin': 'BEN', 'Burkina Faso': 'BFA', 'Bangladesh': 'BGD', 'Bulgaria': 'BGR', 'Bahrain': 'BHR',
                   'Bahamas': 'BHS', 'Bosnia and Herzegovina': 'BIH', 'Belarus': 'BLR', 'Belize': 'BLZ',
                   'Bolivia': 'BOL', 'Brazil': 'BRA', 'Barbados': 'BRB', 'Brunei Darussalam': 'BRN', 'Bhutan': 'BTN',
                   'Botswana': 'BWA', 'Central African Republic': 'CAF', 'Canada': 'CAN', 'Switzerland': 'CHE',
                   'Chile': 'CHL', 'China': 'CHN', "Côte d'Ivoire": 'CIV', 'Cameroon': 'CMR',
                   'Democratic Republic of the Congo': 'COD', 'Congo': 'COG', 'Colombia': 'COL',
                   'Comoros': 'COM', 'Cabo Verde': 'CPV', 'Costa Rica': 'CRI', 'Cuba': 'CUB',
                   'Cyprus': 'CYP', 'Czech Republic': 'CZE', 'Germany': 'DEU', 'Djibouti': 'DJI',
                   'Dominica': 'DMA', 'Denmark': 'DNK', 'Dominican Republic': 'DOM',
                   'Algeria': 'DZA', 'Ecuador': 'ECU', 'Egypt': 'EGY', 'Eritrea': 'ERI',
                   'Spain': 'ESP', 'Estonia': 'EST', 'Ethiopia': 'ETH', 'Finland': 'FIN',
                   'Fiji': 'FJI', 'France': 'FRA', 'Micronesia (Federated States of)': 'FSM',
                   'Gabon': 'GAB', 'United Kingdom': 'GBR', 'Georgia': 'GEO', 'Ghana': 'GHA',
                   'Guinea': 'GIN', 'Gambia': 'GMB', 'Guinea-Bissau': 'GNB', 'Equatorial Guinea': 'GNQ',
                   'Greece': 'GRC', 'Grenada': 'GRD', 'Guatemala': 'GTM', 'Guyana': 'GUY', 'Honduras': 'HND',
                   'Croatia': 'HRV', 'Haiti': 'HTI', 'Hungary': 'HUN', 'Indonesia': 'IDN', 'India': 'IND',
                   'Ireland': 'IRL', 'Iran (Islamic Republic of)': 'IRN', 'Iraq': 'IRQ', 'Iceland': 'ISL',
                   'Israel': 'ISR', 'Italy': 'ITA', 'Jamaica': 'JAM', 'Jordan': 'JOR', 'Japan': 'JPN',
                   'Kazakhstan': 'KAZ', 'Kenya': 'KEN', 'Kyrgyzstan': 'KGZ',
                   'Cambodia': 'KHM', 'Kiribati': 'KIR', 'Saint Kitts and Nevis': 'KNA', 'Republic of Korea': 'KOR',
                   'Kuwait': 'KWT', "Lao People's Democratic Republic": 'LAO', 'Lebanon': 'LBN', 'Liberia': 'LBR',
                   'Libya': 'LBY', 'Saint Lucia': 'LCA', 'Liechtenstein': 'LIE', 'Sri Lanka': 'LKA', 'Lesotho': 'LSO',
                   'Lithuania': 'LTU', 'Luxembourg': 'LUX', 'Latvia': 'LVA', 'Morocco': 'MAR', 'Monaco': 'MCO',
                   'Republic of Moldova': 'MDA', 'Madagascar': 'MDG', 'Maldives': 'MDV', 'Mexico': 'MEX',
                   'Marshall Islands': 'MHL', 'North Macedonia': 'MKD', 'Mali': 'MLI', 'Malta': 'MLT', 'Myanmar': 'MMR',
                   'Montenegro': 'MNE', 'Mongolia': 'MNG', 'Mozambique': 'MOZ', 'Mauritania': 'MRT', 'Mauritius': 'MUS',
                   'Malawi': 'MWI', 'Malaysia': 'MYS', 'Namibia': 'NAM', 'Niger': 'NER', 'Nigeria': 'NGA',
                   'Nicaragua': 'NIC', 'Netherlands': 'NLD', 'Norway': 'NOR', 'Nepal': 'NPL', 'Nauru': 'NRU',
                   'New Zealand': 'NZL', 'Oman': 'OMN', 'Pakistan': 'PAK', 'Panama': 'PAN', 'Peru': 'PER',
                   'Philippines': 'PHL', 'Palau': 'PLW', 'Papua New Guinea': 'PNG', 'Poland': 'POL',
                   "Democratic People's Republic of Korea": 'PRK', 'Portugal': 'PRT', 'Paraguay': 'PRY', 'Qatar': 'QAT',
                   'Romania': 'ROU', 'Russian Federation': 'RUS', 'Rwanda': 'RWA', 'Saudi Arabia': 'SAU', 'Sudan': 'SDN', 'Senegal': 'SEN', 'Singapore': 'SGP', 'Solomon Islands': 'SLB', 'Sierra Leone': 'SLE', 'El Salvador': 'SLV', 'San Marino': 'SMR', 'Somalia': 'SOM', 'Serbia': 'SRB', 'South Sudan': 'SSD', 'Sao Tome and Principe': 'STP', 'Suriname': 'SUR', 'Slovakia': 'SVK', 'Slovenia': 'SVN', 'Sweden': 'SWE', 'Eswatini': 'SWZ', 'Seychelles': 'SYC', 'Syrian Arab Republic': 'SYR', 'Chad': 'TCD', 'Togo': 'TGO', 'Thailand': 'THA', 'Tajikistan': 'TJK', 'Turkmenistan': 'TKM', 'Timor-Leste': 'TLS', 'Tonga': 'TON', 'Trinidad and Tobago': 'TTO', 'Tunisia': 'TUN', 'Turkey': 'TUR', 'Tuvalu': 'TUV', 'United Republic of Tanzania': 'TZA', 'Uganda': 'UGA', 'Ukraine': 'UKR', 'Uruguay': 'URY', 'United States of America': 'USA', 'Uzbekistan': 'UZB', 'Saint Vincent and the Grenadines': 'VCT', 'Venezuela (Bolivarian Republic of)': 'VEN', 'Viet Nam': 'VNM', 'Vanuatu': 'VUT', 'Samoa': 'WSM', 'Yemen': 'YEM', 'South Africa': 'ZAF', 'Zambia': 'ZMB', 'Zimbabwe': 'ZWE'}
